baseURL = "/"
title   = "Terence Ponce's Website"

DefaultContentLanguage = "en"

theme = "hermit"

PygmentsCodeFences = true
pygmentsUseClasses  = true

rssLimit  = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

googleAnalytics = "UA-143255060-1"
disqusShortname = "terenceponce"

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpored = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "Terence Ponce"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag      = "tags"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Personal Website of Terence Ponce"
  keywords = ""
  images = [""]

  homeSubtitle = "Ruby | Elixir | React | React Native | Flutter | Blockchain | DevOps"

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  justifyContent = false  # Set "text-align: justify" to .content.

  themeColor = "#494f5c"

  # Social icons
  [[params.social]]
    name = "email"
    url  = "terenceponce@gmail.com"

  [[params.social]]
    name = "gitlab"
    url  = "https://gitlab.com/terenceponce"

  [[params.social]]
    name = "github"
    url  = "https://github.com/terenceponce"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/terenceponce"

[menu]
  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 10
  [[menu.main]]
    name = "Posts"
    url= "posts/"
    weight = 20
